# Generated by Django 2.1.15 on 2020-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_ID', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(blank=True, max_length=10)),
            ],
        ),
    ]
