# Generated by Django 2.1.15 on 2020-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='phone_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_ID',
            field=models.EmailField(max_length=50),
        ),
    ]
