# Generated by Django 2.1.15 on 2020-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200513_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_ID',
            field=models.EmailField(max_length=254),
        ),
    ]
