# Generated by Django 2.1.15 on 2020-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0008_auto_20200519_1025'),
        ('question', '0005_auto_20200519_1025'),
        ('users', '0005_auto_20200513_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_ID', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
