# Generated by Django 2.1.15 on 2020-05-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questable',
            name='id',
        ),
        migrations.RenameField(
            model_name='quesdetail',
            old_name='created',
            new_name='created_on',
        ),
        migrations.DeleteModel(
            name='QuesTable',
        ),
    ]
