# Generated by Django 2.1.15 on 2020-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_quesdetail_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesdetail',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quesdetail',
            name='title',
            field=models.TextField(),
        ),
    ]
