# Generated by Django 2.1.15 on 2020-05-19 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_question_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 10, 36, 31, 270580), editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 10, 36, 31, 270614)),
        ),
    ]
