# Generated by Django 2.1.15 on 2020-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20200520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
