# Generated by Django 2.1.15 on 2020-05-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200513_0801'),
        ('answer', '0003_ansdetail_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansdetail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserTable'),
        ),
    ]
