# Generated by Django 2.1.15 on 2020-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_ansdetail_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansdetail',
            name='body',
            field=models.TextField(),
        ),
    ]
