# Generated by Django 2.1.15 on 2020-05-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_auto_20200513_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansdetail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='users.UserTable'),
        ),
    ]
