# Generated by Django 2.1.15 on 2020-05-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_auto_20200515_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansdetail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserTable'),
        ),
        migrations.AlterField(
            model_name='ansdetail',
            name='ques',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='question.QuesDetail'),
        ),
    ]
