# Generated by Django 2.1.15 on 2020-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0007_auto_20200515_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ansdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ansdetail',
            name='ques',
        ),
        migrations.DeleteModel(
            name='AnsDetail',
        ),
    ]
