# Generated by Django 2.1.15 on 2020-05-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0011_auto_20200519_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ques',
            new_name='quess',
        ),
    ]
