# Generated by Django 2.1.15 on 2020-05-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0012_auto_20200520_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quess',
            new_name='ques',
        ),
    ]
